In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)
print(tf.version)

2.6.0
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
input1= tf.constant([1, 2, 3])

In [ ]:
input2 = tf.constant([5,2,4])

In [ ]:
output = tf.add(input1, input2)

In [ ]:
print(output)
# session

tf.Tensor([6 4 7], shape=(3,), dtype=int32)


In [ ]:
# Tensor Creation

In [ ]:
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [ ]:
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>


In [ ]:
print(number)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>


In [ ]:
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


In [ ]:
# Rank of the tensor

In [ ]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [ ]:
print(rank1_tensor)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'Test'], dtype=object)>


In [ ]:
print(rank2_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'ok'],
       [b'test', b'yes']], dtype=object)>


In [ ]:
# Shape of the tensor

In [ ]:
rank2_tensor.shape

TensorShape([2, 2])

In [ ]:
# Changing the shape of the tensor

In [ ]:
tensor1 = tf.ones([1,2,3])  
                                                                             

In [ ]:
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [ ]:
tensor2 = tf.reshape(tensor1, [2,3,1])

In [ ]:
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [ ]:
tensor3 = tf.reshape(tensor2, [3, -1])  

In [ ]:
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [ ]:

three = tensor[0,2] 
print(three)  

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
