In [30]:
import numpy as np
import pandas as pd

In [31]:
text = "After sleeping for four hours, he decided to sleep for another four!"


In [32]:
word_list = text.split(' ')
word_list

['After',
 'sleeping',
 'for',
 'four',
 'hours,',
 'he',
 'decided',
 'to',
 'sleep',
 'for',
 'another',
 'four!']

In [33]:
# Regex => Regular Expression | Compiler Design | Theory of computation
import re

In [34]:
sentence = re.sub(r"[^a-zA-Z0-9]+", ' ', text)
sentence

'After sleeping for four hours he decided to sleep for another four '

In [35]:
stop_words = ['a','and', 'the', 'an', 'he', 'she', 'for']

In [36]:
for word in word_list:
    if word not in stop_words:
        print("yes")

yes
yes
yes
yes
yes
yes
yes
yes
yes


In [37]:
refined_wlist = []
for word in word_list:
    if word not in stop_words:
        refined_wlist.append(word)
        
refined_wlist

['After',
 'sleeping',
 'four',
 'hours,',
 'decided',
 'to',
 'sleep',
 'another',
 'four!']

In [38]:
# stemming

In [39]:
stems = ['ing','s', 'ed']

In [40]:
for word in refined_wlist:
    for st in stems:
        if st in word:
            print(word)

sleeping
sleeping
hours,
decided
sleep


In [41]:
new_list = []
for word in refined_wlist:
    flag = 0
    for st in stems:
        if word.find(st)>0:
            new_list.append(word.replace(st,''))
            flag = 1
            break
    if flag == 0:
        new_list.append(word)
            
            

In [42]:
new_list 

['After', 'sleep', 'four', 'hour,', 'decid', 'to', 'sleep', 'another', 'four!']

In [43]:
world_list_l = []

for word in new_list:
    world_list_l.append(word.lower())

world_list_l

['after', 'sleep', 'four', 'hour,', 'decid', 'to', 'sleep', 'another', 'four!']

In [51]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print(lemmatizer.lemmatize("cows"))

cow


In [52]:
tok = ['The', 'striped', 'bats', 'are', 'hanging', 'on', 'their', 'feet', 'for', 'bested']
for t in tok:
    print(lemmatizer.lemmatize(t))

The
striped
bat
are
hanging
on
their
foot
for
bested


In [53]:
sentences = ['it is a good movie', 'it is not a good movie', 'i did not like it']

In [54]:
unique_list = []
token_list = []
for sen in sentences:
    tokens = word_tokenize(sen)
    token_list.append(tokens)
    for tok in tokens:
        if tok not in unique_list:
              unique_list.append(tok)

In [56]:
print(unique_list, token_list)

['it', 'is', 'a', 'good', 'movie', 'not', 'i', 'did', 'like'] [['it', 'is', 'a', 'good', 'movie'], ['it', 'is', 'not', 'a', 'good', 'movie'], ['i', 'did', 'not', 'like', 'it']]


In [57]:
token_list

[['it', 'is', 'a', 'good', 'movie'],
 ['it', 'is', 'not', 'a', 'good', 'movie'],
 ['i', 'did', 'not', 'like', 'it']]

In [58]:
gram_1 = []

for token in token_list:
    # print(token)
    temp_list = []
    for un in unique_list:
          if un in token:
        # print("1")
            temp_list.append(1)
          else:
        # print("0")
            temp_list.append(0)
    print(temp_list)
    gram_1.append(temp_list)

[1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 0, 0, 0, 0, 1, 1, 1, 1]


In [59]:
import numpy as np
np.array(gram_1)

array([[1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 1, 1, 1]])

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
text1 = ["it is a good movie"]
text2 = ["it is not a good movie"]
text3 = ["i did not like it"]

In [61]:
vectorizer = CountVectorizer()
vectorizer.fit(text1)

CountVectorizer()

In [62]:
print(vectorizer.vocabulary_)

{'it': 2, 'is': 1, 'good': 0, 'movie': 3}


In [63]:
newvector = vectorizer.transform(text2)

print(newvector.toarray())

[[1 1 1 1]]


In [64]:
newvector1 = vectorizer.transform(text3)
print(newvector1.toarray())

[[0 0 1 0]]


In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [66]:
text = ["it is a good movie","it is not a good movie","i did not like it"]

In [67]:
vectorizer.fit(text)

TfidfVectorizer()

In [68]:
print(vectorizer.idf_)

[1.69314718 1.28768207 1.28768207 1.         1.69314718 1.28768207
 1.28768207]


In [69]:
print(vectorizer.vocabulary_)

{'it': 3, 'is': 2, 'good': 1, 'movie': 5, 'not': 6, 'did': 0, 'like': 4}


In [70]:
vector = vectorizer.transform([text[2]])

In [71]:
print(vector.toarray())

[[0.5844829  0.         0.         0.34520502 0.5844829  0.
  0.44451431]]


In [72]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]


In [73]:
import pandas as pd

In [74]:
vectorizer = TfidfVectorizer(max_df=0.5, ngram_range=(1,3),
                                 min_df=2,
                                 )
X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(
    X.todense(),
    columns=vectorizer.get_feature_names()
)


print(X.shape)
print(df)

(4, 6)
      first  first document  the first  the first document   this is  \
0  0.408248        0.408248   0.408248            0.408248  0.408248   
1  0.000000        0.000000   0.000000            0.000000  0.000000   
2  0.000000        0.000000   0.000000            0.000000  0.707107   
3  0.500000        0.500000   0.500000            0.500000  0.000000   

   this is the  
0     0.408248  
1     0.000000  
2     0.707107  
3     0.000000  


In [75]:
corpus = [
    'Data mining is one of the important research in the domain of Artificial Intelligence.',
    'Artificial Intelligence is a subject in Computer Science.',
    'Now a days, Artifical Intelligence is most commonly used in machine learning',
    'This particulary statement speaks about Aritifical Intelligence',
]

In [76]:
vectorizer = TfidfVectorizer(max_df=0.4, ngram_range=(1,3),
                                 min_df=1,
                                 )
X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(
    X.todense(),
    columns=vectorizer.get_feature_names()
)
print(df)
df.to_csv('sample.csv')

      about  about aritifical  about aritifical intelligence  aritifical  \
0  0.000000          0.000000                       0.000000    0.000000   
1  0.000000          0.000000                       0.000000    0.000000   
2  0.000000          0.000000                       0.000000    0.000000   
3  0.242536          0.242536                       0.242536    0.242536   

   aritifical intelligence  artifical  artifical intelligence  \
0                 0.000000   0.000000                0.000000   
1                 0.000000   0.000000                0.000000   
2                 0.000000   0.196116                0.196116   
3                 0.242536   0.000000                0.000000   

   artifical intelligence is  artificial intelligence is  commonly  ...  \
0                   0.000000                    0.000000  0.000000  ...   
1                   0.000000                    0.288675  0.000000  ...   
2                   0.196116                    0.000000  0.196116  

In [77]:
vectorizer = TfidfVectorizer(max_df=0.5, ngram_range=(2,2),
                                 min_df=1,
                                 )
X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(
    X.todense(),
    columns=vectorizer.get_feature_names()
)
print(df)
df.to_csv('sample1.csv')

   about aritifical  aritifical intelligence  artifical intelligence  \
0          0.000000                 0.000000                0.000000   
1          0.000000                 0.000000                0.000000   
2          0.000000                 0.000000                0.322386   
3          0.408248                 0.408248                0.000000   

   artificial intelligence  commonly used  computer science  data mining  \
0                 0.221920       0.000000          0.000000     0.281477   
1                 0.344315       0.000000          0.436719     0.000000   
2                 0.000000       0.322386          0.000000     0.000000   
3                 0.000000       0.000000          0.000000     0.000000   

   days artifical  domain of  important research  ...    one of  \
0        0.000000   0.281477            0.281477  ...  0.281477   
1        0.000000   0.000000            0.000000  ...  0.000000   
2        0.322386   0.000000            0.000000  ...  0.

In [79]:
data_train = pd.read_csv('data_train.csv', encoding='utf-8')
data_test = pd.read_csv('data_test.csv', encoding='utf-8')

X_train = data_train.Text
X_test = data_test.Text

y_train = data_train.Emotion
y_test = data_test.Emotion

data = data_train.append(data_test, ignore_index=True)

In [78]:
class_names = ['joy', 'fear', 'anger', 'sadness', 'neutral']

In [80]:
data

Emotion                                               Text
0      neutral   There are tons of other paintings that I thin...
1      sadness  Yet the dog had grown old and less capable , a...
2         fear  When I get into the tube or the train without ...
3         fear  This last may be a source of considerable disq...
4        anger  She disliked the intimacy he showed towards so...
...        ...                                                ...
11322  sadness  My sweetheart left me, or rather we decided to...
11323  sadness  Well , it's too bad that we like different kin...
11324  neutral                                      It sure is . 
11325  sadness  He ’ s got laid off again . I do feel sorry fo...
11326    anger  When stupid people push me during rush time in...

[11327 rows x 2 columns]

In [81]:
print(data.Emotion.value_counts())

joy        2326
sadness    2317
anger      2259
neutral    2254
fear       2171
Name: Emotion, dtype: int64


In [82]:
data.Emotion.unique()

array(['neutral', 'sadness', 'fear', 'anger', 'joy'], dtype=object)

In [84]:
fear_df = data[data['Emotion']=='fear'].head(10)
fear_df

Emotion                                               Text
2     fear  When I get into the tube or the train without ...
3     fear  This last may be a source of considerable disq...
10    fear  I had gone to the hospital for my research and...
17    fear  When I have to leave the baby in the carriage ...
20    fear     Infiltration in our lives. The illusion of ...
34    fear  When biking and I felt very bad (problems with...
35    fear  Whenever I am alone in a dark room, walk alone...
37    fear  When I got in jungle where there was a great n...
49    fear  When I was involved in a car accident last Nov...
53    fear      Saw a classmate knocked down by a motorcycle.

In [88]:
vectorizer = TfidfVectorizer(max_df=0.5, ngram_range=(1,1),
                                 min_df=1,
                                 )
X = vectorizer.fit_transform(fear_df.Text)
emotion_v = pd.DataFrame(
    X.todense(),
    columns=vectorizer.get_feature_names()
)
print(emotion_v)
emotion_v.to_csv('emotion_v.csv')

     accept  accident     after     alone        am        an       and  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.112720   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.112480   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.148407   
4  0.296792  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.392984   
6  0.000000  0.000000  0.000000  0.467241  0.155747  0.155747  0.000000   
7  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8  0.000000  0.142548  0.142548  0.000000  0.000000  0.000000  0.169296   
9  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         as        at      baby  ...       was        we  whenever     where  \
0  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
1  0.161366  0

In [89]:
neutral_df = data[data['Emotion']=='neutral'].head(10)
neutral_df

Emotion                                               Text
0   neutral   There are tons of other paintings that I thin...
8   neutral                                             Yes . 
14  neutral   Perhaps we need to have more babies ! Tina ga...
15  neutral                                             Why ? 
23  neutral                                      Over there . 
25  neutral   Me , too , I can ’ t stop scratching . They a...
28  neutral                                             Why ? 
50  neutral                                             Why ? 
54  neutral                                         Make it 4 
66  neutral                                             Jim !

In [90]:
vectorizer = TfidfVectorizer(max_df=0.5, ngram_range=(1,1),
                                 min_df=1,
                                 )
X = vectorizer.fit_transform(neutral_df.Text)
emotion_v1 = pd.DataFrame(
    X.todense(),
    columns=vectorizer.get_feature_names()
)
print(emotion_v1)

        are  babies  baby    better  birth   boy       can  everywhere  gave  \
0  0.521880    0.00  0.00  0.306955   0.00  0.00  0.000000    0.000000  0.00   
1  0.000000    0.00  0.00  0.000000   0.00  0.00  0.000000    0.000000  0.00   
2  0.000000    0.25  0.25  0.000000   0.25  0.25  0.000000    0.000000  0.25   
3  0.000000    0.00  0.00  0.000000   0.00  0.00  0.000000    0.000000  0.00   
4  0.000000    0.00  0.00  0.000000   0.00  0.00  0.000000    0.000000  0.00   
5  0.259606    0.00  0.00  0.000000   0.00  0.00  0.305386    0.305386  0.00   
6  0.000000    0.00  0.00  0.000000   0.00  0.00  0.000000    0.000000  0.00   
7  0.000000    0.00  0.00  0.000000   0.00  0.00  0.000000    0.000000  0.00   
8  0.000000    0.00  0.00  0.000000   0.00  0.00  0.000000    0.000000  0.00   
9  0.000000    0.00  0.00  0.000000   0.00  0.00  0.000000    0.000000  0.00   

   have  ...      they     think  tina   to      tons       too    we  why  \
0  0.00  ...  0.000000  0.306955  0.00  0