In [2]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\shubdutta\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shubdutta\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\shubdutta\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [3]:
text = "After sleeping for four hours, he decided to sleep for another four"
tokens = word_tokenize(text)
print(tokens)

['After', 'sleeping', 'for', 'four', 'hours', ',', 'he', 'decided', 'to', 'sleep', 'for', 'another', 'four']


In [4]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [5]:


example_sent = "This is a sample sentence, showing off the stop words filtration."

stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(example_sent)

filtered_sentence = [w for w in word_tokens if not w in stop_words]

filtered_sentence = []

for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)

print(word_tokens)
print(filtered_sentence)

['This', 'is', 'a', 'sample', 'sentence', ',', 'showing', 'off', 'the', 'stop', 'words', 'filtration', '.']
['This', 'sample', 'sentence', ',', 'showing', 'stop', 'words', 'filtration', '.']


In [6]:
text = "The United States of America (USA) or America, is a federal republic composed of 50 states"
print(text)
print(text.lower())

The United States of America (USA) or America, is a federal republic composed of 50 states
the united states of america (usa) or america, is a federal republic composed of 50 states


In [7]:
def text_cleaner(text):
    rules = [
        {r'>\s+': u'>'},  # remove spaces after a tag opens or closes
        {r'\s+': u' '},  # replace consecutive spaces
        {r'\s*<br\s*/?>\s*': u'\n'},  # newline after a <br>
        {r'</(div)\s*>\s*': u'\n'},  # newline after </p> and </div> and <h1/>...
        {r'</(p|h\d)\s*>\s*': u'\n\n'},  # newline after </p> and </div> and <h1/>...
        {r'<head>.*<\s*(/head|body)[^>]*>': u''},  # remove <head> to </head>
        {r'<a\s+href="([^"]+)"[^>]*>.*</a>': r'\1'},  # show links instead of texts
        {r'[ \t]*<[^<]*?/?>': u''},  # remove remaining tags
        {r'^\s+': u''}  # remove spaces at the beginning
    ]
    for rule in rules:
      for (k, v) in rule.items():
          regex = re.compile(k)
          text = regex.sub(v, text)
          text = text.rstrip()
    return text.lower()

In [ ]:
# from autocorrect import spell

# print(spell('caaaar'))
# print(spell(u'mussage'))
# print(spell(u'survice'))


In [8]:
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

ps = PorterStemmer()

example_words = ["python","pythoner","pythoning","pythoned","pythonly"]

for w in example_words:
  print(ps.stem(w))

python
python
python
python
pythonli


In [16]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

print(lemmatizer.lemmatize("cows"))

cow


In [18]:
tok = ['The', 'striped', 'bats', 'are', 'hanging', 'on', 'their', 'feet', 'for', 'bested']
for t in tok:
    print(lemmatizer.lemmatize(t))

The
striped
bat
are
hanging
on
their
foot
for
bested


In [19]:
sentences = ['it is a good movie', 'it is not a good movie', 'i did not like it']


In [20]:
unique_list = []
token_list = []
for sen in sentences:
    tokens = word_tokenize(sen)
    token_list.append(tokens)
    for tok in tokens:
        if tok not in unique_list:
              unique_list.append(tok)

In [21]:
print(unique_list, token_list)

['it', 'is', 'a', 'good', 'movie', 'not', 'i', 'did', 'like'] [['it', 'is', 'a', 'good', 'movie'], ['it', 'is', 'not', 'a', 'good', 'movie'], ['i', 'did', 'not', 'like', 'it']]


In [23]:
token_list

[['it', 'is', 'a', 'good', 'movie'],
 ['it', 'is', 'not', 'a', 'good', 'movie'],
 ['i', 'did', 'not', 'like', 'it']]

In [26]:
gram_1 = []

for token in token_list:
    # print(token)
    temp_list = []
    for un in unique_list:
          if un in token:
        # print("1")
            temp_list.append(1)
          else:
        # print("0")
            temp_list.append(0)
    print(temp_list)
    gram_1.append(temp_list)

[1, 1, 1, 1, 1, 0, 0, 0, 0]
[1, 1, 1, 1, 1, 1, 0, 0, 0]
[1, 0, 0, 0, 0, 1, 1, 1, 1]


In [29]:
import numpy as np

In [30]:
np.array(gram_1)

array([[1, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 1, 1, 1]])

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
text1 = ["it is a good movie"]
text2 = ["it is not a good movie"]
text3 = ["i did not like it"]

In [49]:
vectorizer = CountVectorizer()
vectorizer.fit(text1)

CountVectorizer()

In [50]:
print(vectorizer.vocabulary_)

{'it': 2, 'is': 1, 'good': 0, 'movie': 3}


In [34]:
newvector = vectorizer.transform(text2)

print(newvector.toarray())

[[1 1 1 1]]


In [35]:
newvector1 = vectorizer.transform(text3)
print(newvector1.toarray())

[[0 0 1 0]]


In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [40]:
text = ["it is a good movie","it is not a good movie","i did not like it"]

In [46]:
vectorizer.fit(text)

TfidfVectorizer()

In [47]:
print(vectorizer.idf_)

[1.69314718 1.28768207 1.28768207 1.         1.69314718 1.28768207
 1.28768207]


In [48]:
print(vectorizer.vocabulary_)

{'it': 3, 'is': 2, 'good': 1, 'movie': 5, 'not': 6, 'did': 0, 'like': 4}


In [44]:
vector = vectorizer.transform([text[2]])

In [45]:
print(vector.toarray())

[[0. 0. 1. 0.]]


In [51]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

import pandas as pd

In [52]:
vectorizer = TfidfVectorizer(max_df=0.5, ngram_range=(1,3),
                                 min_df=2,
                                 )
X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(
    X.todense(),
    columns=vectorizer.get_feature_names()
)


print(X.shape)
print(df)

(4, 6)
      first  first document  the first  the first document   this is  \
0  0.408248        0.408248   0.408248            0.408248  0.408248   
1  0.000000        0.000000   0.000000            0.000000  0.000000   
2  0.000000        0.000000   0.000000            0.000000  0.707107   
3  0.500000        0.500000   0.500000            0.500000  0.000000   

   this is the  
0     0.408248  
1     0.000000  
2     0.707107  
3     0.000000  


In [53]:
orpus = [
    'Data mining is one of the important research in the domain of Artificial Intelligence.',
    'Artificial Intelligence is a subject in Computer Science.',
    'Now a days, Artifical Intelligence is most commonly used in machine learning',
    'This particulary statement speaks about Aritifical Intelligence',
]

In [54]:
vectorizer = TfidfVectorizer(max_df=0.4, ngram_range=(1,3),
                                 min_df=1,
                                 )
X = vectorizer.fit_transform(corpus)
df = pd.DataFrame(
    X.todense(),
    columns=vectorizer.get_feature_names()
)
print(df)
df.to_csv('sample.csv')

        and  and this  and this is  document is  document is the  \
0  0.000000  0.000000     0.000000     0.000000         0.000000   
1  0.000000  0.000000     0.000000     0.333333         0.333333   
2  0.333333  0.333333     0.333333     0.000000         0.000000   
3  0.000000  0.000000     0.000000     0.000000         0.000000   

   is the first  is the second  is the third  is this  is this the  ...  \
0           1.0       0.000000      0.000000      0.0          0.0  ...   
1           0.0       0.333333      0.000000      0.0          0.0  ...   
2           0.0       0.000000      0.333333      0.0          0.0  ...   
3           0.0       0.000000      0.000000      0.5          0.5  ...   

   the second  the second document  the third  the third one     third  \
0    0.000000             0.000000   0.000000       0.000000  0.000000   
1    0.333333             0.333333   0.000000       0.000000  0.000000   
2    0.000000             0.000000   0.333333       0.333333 